### ISSUE TITLE
API通信遇到错误：peer closed connection without sending complete message body

### ISSUE THREAD

**Issue by withyou971** [TsinghuaDatabaseGroup/DB-GPT#122]
==============================Data chat Configuration==============================
操作系统：Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35.
python版本：3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0]
项目版本：v0.0.1
langchain版本：0.0.344. fastchat版本：0.2.36

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['qwen_18b'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/mnt/g/chatglm/db-gpt-qh/model/Qwen-1_8B-Chat',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： text-embedding-ada-002 @ cuda

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    DB-GPT  API  Server: http://127.0.0.1:7861
    DB-GPT WEBUI Server: http://0.0.0.0:8501
==============================DB-GPT Configuration==============================

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8501

2024-03-28 15:48:03,012 - _client.py[line:1026] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:59642 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-28 15:48:03,020 - _client.py[line:1026] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-03-28 15:48:03,159 - _client.py[line:1026] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:59642 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-28 15:48:03,167 - _client.py[line:1026] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:59642 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-03-28 15:48:03,174 - _client.py[line:1026] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
2024-03-28 15:48:07,116 - _client.py[line:1026] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:37774 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-28 15:48:07,126 - _client.py[line:1026] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-03-28 15:48:07,162 - _client.py[line:1026] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:37774 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-28 15:48:07,168 - _client.py[line:1026] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:37774 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-03-28 15:48:07,176 - _client.py[line:1026] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:37774 - "POST /chat/chat HTTP/1.1" 200 OK
2024-03-28 15:48:07,212 - _client.py[line:1026] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/mnt/g/chatglm/DB-GPT-qh/server/chat/chat.py", line 44, in chat_iterator
    message_id = add_message_to_db(chat_type="llm_chat", query=query, conversation_id=conversation_id)
  File "/mnt/g/chatglm/DB-GPT-qh/server/db/session.py", line 26, in wrapper
    result = f(session, *args, **kwargs)
  File "/mnt/g/chatglm/DB-GPT-qh/server/db/repository/message_repository.py", line 19, in add_message_to_db
    session.commit()
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1920, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1236, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1211, in _prepare_impl
    self.session.flush()
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4163, in flush
    self._flush(objects)
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4298, in _flush
    with util.safe_reraise():
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4259, in _flush
    flush_context.execute()
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1226, in _emit_insert_statements
    result = connection.execute(
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/root/anaconda3/envs/dbgpts/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: message
[SQL: INSERT INTO message (id, conversation_id, chat_type, "query", response, meta_data, feedback_score, feedback_reason, create_time) VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP) RETURNING create_time]
[parameters: ('0f9509e43907405b94374347e22029c6', 'b6ee1b1811e34f35a8819ba5541b4eff', 'llm_chat', 'hello', '', '{}', -1, '')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-28 15:48:07,238 - utils.py[line:187] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**Comment by withyou971** [comment]
需要初始化知识库
